name: CI Pipeline
on: push
jobs:
  run_jUnit_tests:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[CI Test]')"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run tests with Maven
        run: mvn -B test --file pom.xml
  depecheck_test:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[CI DepCheck]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build project with Maven
        run: mvn clean install
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'    
          args: >
            --failOnCVSS 7
            --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports
  publish_Project_job:
    runs-on: ubuntu-latest
    needs: [run_jUnit_tests, depecheck_test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - run: mvn -B package --file pom.xml -DskipTests
      - run: mkdir staging
      - uses: actions/upload-artifact@v1
        with:
          name: Package
          path: staging